name: Lint report

on:
  workflow_call:

jobs:
  lint-report:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: tox -e lint